[package]
name = "RustUITestApp"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies.windows-sys]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]
windows = "0.36.0"
